# Generated by Django 4.2.6 on 2023-10-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
