# Generated by Django 4.2.6 on 2023-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_student_details_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
