# Generated by Django 4.2.6 on 2023-11-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_details',
        ),
    ]
