# Generated by Django 4.2.6 on 2023-11-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_admin_admin_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_details',
            old_name='pasword',
            new_name='password',
        ),
    ]
