# Generated by Django 4.2.6 on 2023-11-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_pasword_admin_details_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='password',
            field=models.DateField(blank=True, null=True),
        ),
    ]
