# Generated by Django 4.2.6 on 2023-11-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_student_details_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='password',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
