# Generated by Django 4.2.6 on 2023-11-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_student_password_alter_student_details_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='roll_no',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='roll_no',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
