# Generated by Django 4.2.6 on 2023-11-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_grade_roll_no_alter_student_details_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
