# Generated by Django 4.2.6 on 2023-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_teacher_course1_alter_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_details',
            name='roll_no',
            field=models.CharField(default='22', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course1',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False),
        ),
    ]
