# Generated by Django 4.2.6 on 2023-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_student_details_id_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course1',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
