# Generated by Django 4.2.6 on 2023-11-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_student_details_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='year',
        ),
    ]
