# Generated by Django 4.2.6 on 2023-11-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_marks_branch_remove_marks_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='course_key',
        ),
    ]
