# Generated by Django 4.2.6 on 2023-11-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_course_course_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher',
            new_name='course',
        ),
    ]
