# Generated by Django 4.2.6 on 2023-11-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_teacher_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marks',
            new_name='mark',
        ),
    ]
