# Generated by Django 4.2.6 on 2023-11-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_marks_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_details',
            new_name='admin_detail',
        ),
        migrations.RenameModel(
            old_name='student_details',
            new_name='student_detail',
        ),
    ]
