# Generated by Django 4.2.6 on 2023-11-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
