# Generated by Django 4.2.6 on 2023-11-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_detail',
            name='name',
            field=models.CharField(blank=True, default='abc', max_length=150, null=True),
        ),
    ]
