# Generated by Django 4.2.6 on 2023-11-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_admin_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_detail',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
