# Generated by Django 4.2.6 on 2024-04-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_admin_detail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_key',
            name='entered_marks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_key',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_key',
            name='total_marks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
