# Generated by Django 4.2.6 on 2024-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_course_key_entered_marks_course_key_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_courses', models.CharField(blank=True, max_length=255, null=True)),
                ('entered_courses', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
