# Generated by Django 4.2.6 on 2023-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_mark_ct1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mark',
        ),
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
