# Generated by Django 4.2.6 on 2023-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_marks_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='score',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
