# Generated by Django 4.2.6 on 2023-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_marks_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='score',
            field=models.CharField(blank=True, default='z', max_length=1),
        ),
    ]
