# Generated by Django 4.2.6 on 2023-10-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_marks_ct1_alter_marks_ct2_alter_marks_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
