# Generated by Django 4.2.6 on 2023-10-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_grade_cgpa_alter_grade_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
