name: Django CI Tests

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on the latest version of Ubuntu

    steps:

      - name: Run tests
        run: |
          python manage.py test  # Run the Django tests

