name: Django CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: echo "DJANGO_SETTINGS_MODULE=myproject.settings" >> $GITHUB_ENV

      - name: Set up the database
        run: |
          sleep 10
          python manage.py migrate

      - name: Run tests
        run: python manage.py test
        working-directory: ./web_miniproject

      - name: Collect static files (optional)
        run: |
          python manage.py collectstatic --noinput

      - name: Upload test results (optional)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.xml
